import "./globals.css";
import ToastContainerComponent from "./component/ToastContainerComponent.";
import Footer from "./component/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
      <body>
        <ToastContainerComponent />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
